apiVersion: v1
kind: Pod # Type of object
metadata:  # Data about object
  name: myapp-pod
  labels:
    app: myapp
    type: front-end
spec: # provides additional information, container image in case of pods.
  containers:
    - name: nginx-container
      image: nginx
